{% set name = "sigopt" %}
{% set version = "3.4.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "88e149aee6a771018b5f5a7ae7adfa317eec780801758799495c0f7c8873c872" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - requests >=2.11.1
    - setuptools
  run:
    - python
    - requests >=2.11.1

test:
  imports:
    - sigopt
    - sigopt.vendored

about:
  home: http://github.com/sigopt/sigopt-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SigOpt Python API Client'

extra:
  recipe-maintainers:
    - pfhayes
    - alexandraj777 
