{% set name = "sigopt" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89252f80509030e38107c0e0b3961eaf4ad236b629ea4e5ababa6395d19c7373

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - requests >=2.11.1
    - pip
  run:
    - python >=3.6
    - requests >=2.11.1

test:
  imports:
    - sigopt
    - sigopt.vendored

about:
  home: http://github.com/sigopt/sigopt-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SigOpt Python API Client

extra:
  recipe-maintainers:
    - dwanderson-intel
