{% set name = "sigopt" %}
{% set version = "3.5.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "b0d6062b8c4a5eb6efa268065de887a680f0690e1a33670eb3d4b81677b884f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - requests >=2.11.1
    - pip
  run:
    - python
    - requests >=2.11.1

test:
  imports:
    - sigopt
    - sigopt.vendored

about:
  home: http://github.com/sigopt/sigopt-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SigOpt Python API Client'

extra:
  recipe-maintainers:
    - pfhayes
    - alexandraj777 
