{% set name = "sigopt" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45d3613b1d51f099319326fe48618588767585845b84814f7628b249caaaa1fd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - requests >=2.11.1
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.11.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - sigopt
    - sigopt.vendored

about:
  home: http://github.com/sigopt/sigopt-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SigOpt Python API Client

extra:
  recipe-maintainers:
    - dwanderson-intel
