travis:
  secure:
    BINSTAR_TOKEN: kuClTe5OscCgtPQdINB36gXMSowQz1bZKzlSU2FcLKkWmO4PFtJwt5oS1ezy27Lr0v4d/UnDitLAHH/n/uPgYhwmzZyyOJDD8NJ6LoGRNBqmvSLSFEDw+rWxylmPuzNydeM3r+u64Hrjt4Q8q61GLSuBUTyxA+Q8/JvqM9UsMZZwIBkqV9cyRy6fnBpPz7jWGPty65BqrsUIom7mXxqyYoR4qFyqb+viZmtcZfd0SPCZP9ULmNmalnvTHRmqmvw178NeTkPzOq0Fo/lzS28CGs+Skrtz7+jsbYtH5THN1PBhvgIXWJ1AcjPefxjXEcxSzuR8Mef1X8UEgWuw160/mQp8Jk4J9L6mSYDFis+hXKpIl1sWn6rGjE2gLy6u7FwZLHCA6yhnfFa7o+Ny5orOOsgTmoUhPNdgVxnUCLhHO+sCEODGkTAjHTU2QCB1gkm9XE/9yXgF2Dy1uIo7XGOiikAHxq0dbbg3poNuImu25uDncmt1vrqXrrDoLhWELIxR/WHEu2/gCTvLedBR2/s1W0kVRamTQox97pCN2rl77RFfbv15C4oU5fJqFcUz21EXclUIullFhokFnV90OOhxFwCBa+AXQNT9NCK23R5gSpCxujWYQAp6uILULe0y9kKLFZJx1oB2IVVMKeJwEHWdVgweIMbKuvhsakmstwA7fSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
