travis:
  secure:
    BINSTAR_TOKEN: OAYHIdsgFDkoUIebiQhONdfARRP60KIcDjYX9R9OVZzcpUj1kNaOpDSxvBzHPyC4l9m/HvpxlOt089CkQRALnk24l2v6GO48Bzz/4M2nd6jZUuXms0xjdQ0U/fSQbYR2RYHNmgMnZ49uhl7jldv5mZAmp67gs0ZXCVpuK9keZ1wVVDiNkkiKh7gblnjDrWiMUjG+4cno9//osSqAk4cmfNDSlYS77SkZrh4VVP3vHnOiqVWLH35wichsT15FgZZuyl97DDuRqoGl+hABMUZKCAvoyKbfLZla0HQhlg4ynEgKxoqy2QGdiXj+ZAILcMnyAuauH/S/nWgoXWTPP2Cl3p25D/AkZTXoy3uHDZFjyqxPQq0z1R0tx6ZTCv5JyooR+y7TwWjwiaw8ruxRegncF+qHV0Unz+MrxfbPWINcPoGHSvoiFjZmkxOTzHW8RBKGv8kpFq6bveDgGp6aOcWtU9YBWHYfsvsrM+0Av0O4rC9J/N5Npp1EVKSgwV7l4fgMEtTXT5nhiPmN/uYU+/QxoXOtwcfbImR+zlrgZ7kpqKLeZQZnUxA+c6QoqtCEPimA3ZObDxhzZdjV1G3CBiFGOjFckkZ1g8A9t2BYerGGK7bKKoEaiXPwz/EAMxNVob3Octx8Y+hkBvGN0+6eEK/VtV+UYq6CFjMVDYs+wLbbMcY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
